RUN git clone https://github.com/dom2/Project_Medusa.git

WORKDIR /Project_Medusa

RUN npm install --silent
RUN npm install react-scripts@1.1.1 -g --silent
EXPOSE 3000
# start app
CMD ["npm", "start"]
